### ISSUE TITLE
Bug: add food levert http 500

### ISSUE THREAD

**Issue by atienkamp** [slt-programmers/macrologWebapp#33]
POST https://macrolog-backend.herokuapp.com/food/ 500
main.c60129651b131f224be3.js:1 Error interceptor negative t {headers: n, status: 500, statusText: "OK", url: "https://macrolog-backend.herokuapp.com/food/", ok: false, …}error: {timestamp: "2019-04-11T09:11:10.435+0000", status: 500, error: "Internal Server Error", message: "PreparedStatementCallback; bad SQL grammar [insert…ion: Unknown column 'measurement' in 'field list'", path: "/food/"}headers: n {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}message: "Http failure response for https://macrolog-backend.herokuapp.com/food/: 500 OK"name: "HttpErrorResponse"ok: falsestatus: 500statusText: "OK"url: "https://macrolog-backend.herokuapp.com/food/"__proto__: Object
main.c60129651b131f224be3.js:1 Else in interceptor, WHY?

**Comment by atienkamp** [comment]
Browser: Chrome
Geen foutmelding getoond op scherm, simpelweg niets toegevoegd :(

**Comment by CarmenScholte** [comment]
Seems fixed
