### ISSUE TITLE
Bug: user settings with startdate today causes issue (goalless diary) on newly added user

### ISSUE THREAD

**Issue by atienkamp** [slt-programmers/macrologWebapp#34]
Sinds we ondersteunen dat user settings een begindatum hebben, om doelen in het verleden te kunnen ondersteunen, is er een bug ontstaan bij het aanmaken van een nieuwe gebruiker.
Bij het aanmaken krijgen de ingevulde initiele gegevens ook begindatum vandaag. 
Dit is niet handig, want als je terugbladert in het dagboek heb je nog geen settings en dus geen doelen.

- Bij invullen intake wordt de datum van de user settings ver in het verleden gezet 
- Bij het aanpassen van bestaande settings op de user pagina wordt de datum van vandaag mee gegeven

Zet de 1e keer de datum op 1-1-1970 oid.

**Comment by CarmenScholte** [comment]
Andere aanpak genomen zoals gisteravond besproken. Bij call naar valide setting wordt eerst gezocht naar de eerst vorige opgeslagen zetten ten opzichte van de date van de call. Als die niet gevonden wordt (zoals bij terugbladeren in de diary als nieuwe gebruiker) kijk dan naar de eerst volgende geldige setting ten opzichte van de date van de call. 
Nog steeds niks, return null (kan alleen voorkomen als de onboarding is overgeslagen).
