### ISSUE TITLE
Bug: when adding a logentry, switching between 100 grams and portions is buggy

### ISSUE THREAD

**Issue by CarmenScholte** [slt-programmers/macrologWebapp#43]
When selecting a food 100gr from the dropdown, the dropdowns amount and type of unit (for 100 or a portion) is empty. The amount isn't set to 100 and the descriptive string "grams" isn't set properly.

When selecting a food portion from the dropdown, and then switching between portions has no effect on the total calories/macros.

- [ ] The dropdown now shows food only, no more portions
- [ ] The dropdown items can be selected with the arrow keys (up/down) once again
- [ ] When adding a new logentry, the portion is set to grams initially
- [ ] When reopening an existing logentry, the portion is set correctly (if the logentry has a selected portion)

**Comment by atienkamp** [comment]
![image](https://user-images.githubusercontent.com/6122349/61931196-46340600-af80-11e9-91db-0afa55bf791a.png)

Input dropdown and amount should be switched.

**Comment by CarmenScholte** [comment]
New issue for improving portion <--> amount autofill behaviour.
