### ISSUE TITLE
Bug: When adding new food with portions, not all portions are saved

### ISSUE THREAD

**Issue by atienkamp** [slt-programmers/macrologWebapp#47]
In het add food popup you can add several portions.

When adding a food with multiple portions, not all portions are saved.

Use case:
Food page --> Big Plus button
food + macros
+ -> name + grams
+ -> name + grams
+ -> name + grams
+ -> name + grams
save
then we only see 2 portions in the food page. Also a refresh doesnt show them

Unclear if its is a problem with sending a proper request of with saving in the backend

**Comment by atienkamp** [comment]
Added a dummy setcalories to let JSON mapping not complain about unresolved calories while receiving AddFoodRequest with PortionDto, with  calories filled.

**Comment by CarmenScholte** [comment]
Cant reproduce locally

**Comment by CarmenScholte** [comment]
Can't reproduce on prod
